// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// engine_pdist
arma::mat engine_pdist(arma::cube data, std::string name);
RcppExport SEXP _RiemBase_engine_pdist(SEXP dataSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(engine_pdist(data, name));
    return rcpp_result_gen;
END_RCPP
}
// engine_pdist2
arma::mat engine_pdist2(arma::cube data1, arma::cube data2, std::string name);
RcppExport SEXP _RiemBase_engine_pdist2(SEXP data1SEXP, SEXP data2SEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(engine_pdist2(data1, data2, name));
    return rcpp_result_gen;
END_RCPP
}
// engine_median
Rcpp::List engine_median(arma::cube data, std::string name, int maxiter, double eps);
RcppExport SEXP _RiemBase_engine_median(SEXP dataSEXP, SEXP nameSEXP, SEXP maxiterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(engine_median(data, name, maxiter, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiemBase_engine_pdist", (DL_FUNC) &_RiemBase_engine_pdist, 2},
    {"_RiemBase_engine_pdist2", (DL_FUNC) &_RiemBase_engine_pdist2, 3},
    {"_RiemBase_engine_median", (DL_FUNC) &_RiemBase_engine_median, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiemBase(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
