# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

engine_pdist <- function(data, name) {
    .Call('_RiemBase_engine_pdist', PACKAGE = 'RiemBase', data, name)
}

engine_pdist2 <- function(data1, data2, name) {
    .Call('_RiemBase_engine_pdist2', PACKAGE = 'RiemBase', data1, data2, name)
}

